### ISSUE TITLE
Error: java.lang.IndexOutOfBoundsException: Index: 1, Size: 0

### ISSUE THREAD

**Issue by lihb001** [ridgelab/ssva#1]
Hi Developers,
I meet some error when runing ssva. I thinks this may be a bug, so I need you help.

I run command as below:
$ **java -jar /work/Software/SSVA-1.0/target/SSVA-1.0-jar-with-dependencies.jar -i /mnt/resource/lihb_project/tmp/test/test.combined.vcf -o /mnt/resource/lihb_project/tmp/test/Splicing -a /work/Software/annovar_2018-04-16 -d /work/Database/Annovar_db/hg38_20180130 -b hg38 -g /work/Database/GATK_db/Other_RefGenome/hg38_rmContig/Split_Chr -m /work/Software/SSVA-1.0/MES**

Existing avinput file found: test.combined.vcf.avinput
Running Gene Annotation
Running 1000 Genomes MAF Annotation
Running Exac Annotation
Running dbscSNV Annotation
Going through the variants
[.                                                 ] 3.18%java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at analyzer.variantInfo.Variant.parseSpliceInfo(Variant.java:210)
	at analyzer.SpliceRunner.run(SpliceRunner.java:104)
	at analyzer.SpliceEngine.main(SpliceEngine.java:24)

*******************************
The tempory avinput file as below:
[test.combined.vcf.zip](https://github.com/ridgelab/ssva/files/2753828/test.combined.vcf.zip)

Thanks!

**Comment by ridgelab** [comment]
We've updated SSVA with a patch that should address this issue. Please let us know if you are still experiencing the error.

**Comment by lihb001** [comment]
Hi Developers,
I run git clone the ssva, and reinstall.

Then I run command as below, but the result file is empty.

$ java -jar /work/Software/SSVA-1.0/target/SSVA-1.0-jar-with-dependencies.jar -i /mnt/resource/lihb_project/tmp/test/test.combined.vcf -o /mnt/resource/lihb_project/tmp/test/Splicing -a /work/Software/annovar_2018-04-16 -d /work/Database/Annovar_db/hg38_20180130 -b hg38 -g /work/Database/GATK_db/Other_RefGenome/hg38_rmContig/Split_Chr -m /work/Software/SSVA-1.0/MES/
Existing avinput file found: test.combined.vcf.avinput
Existing .variant_function file found: test.combined.vcf.avinput.variant_function
Running 1000 Genomes MAF Annotation
Running Exac Annotation
Running dbscSNV Annotation
Going through the variants
[..................................................] 100.00%

Result directory:
[Splicing.tar.gz](https://github.com/ridgelab/ssva/files/2794635/Splicing.tar.gz)

**Comment by ridgelab** [comment]
We've updated SSVA with another patch. Please let us know if this is still an issue.

**Comment by lihb001** [comment]
Hi Developers!
I reinstall SSVA and run command as before, but the result file is also empty without error reported.

Could you share me a test vcf file that you have test successfully.

Now I confuse what the matter happen to me.

-------------------------
$ java -jar /work/Software/SSVA-1.0/target/SSVA-1.0-jar-with-dependencies.jar -i /mnt/resource/lihb_project/tmp/test/test.combined.vcf -o /mnt/resource/lihb_project/tmp/test/Splicing -a /work/Software/annovar_2018-04-16 -d /work/Database/Annovar_db/hg38_20180130 -b hg38 -g /work/Database/GATK_db/Other_RefGenome/hg38_rmContig/Split_Chr -m /work/Software/SSVA-1.0/MES
Existing avinput file found: test.combined.vcf.avinput
Existing .variant_function file found: test.combined.vcf.avinput.variant_function
Running 1000 Genomes MAF Annotation
lRunning Exac Annotation
Running dbscSNV Annotation
Going through the variants
[..................................................] 100.00%
